package openai

import (
	"bufio"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

// ChatCompletionResponse represents a response from the chat completion endpoint.
type ChatCompletionResponse struct {
	// Type of the object, typically "chat.completion".
	Object string `json:"object"`

	// Unique identifier for the chat completion.
	ID string `json:"id"`

	// The model used for generating the completion.
	Model string `json:"model"`

	// List of completion choices generated by the model.
	Choices []*Choice `json:"choices"`

	// Token usage statistics.
	Usage *Usage `json:"usage"`

	// Timestamp when the chat completion was created.
	Created int64 `json:"created"`
}

// Choice represents a completion choice generated by the model.
type Choice struct {
	// Index of the choice in the list of choices.
	Index int `json:"index"`

	// The message generated by the model.
	Message *Message `json:"message"`

	// Reason why the completion finished.
	FinishReason string `json:"finish_reason"`
}

// Message represents a message generated by the model.
type Message struct {
	// Role of the message sender (e.g., "user", "assistant").
	Role string `json:"role"`

	// Content of the message.
	Content string `json:"content"`

	// Optional reasoning content.
	ReasoningContent string `json:"reasoning_content,omitempty"`

	// Optional tool calls.
	ToolCalls []*ToolCall `json:"tool_calls,omitempty"`

	// Optional audio output.
	Audio *Audio `json:"audio,omitempty"`
}

// ChatCompletionStream is a response stream.
type ChatCompletionStream struct {
	resp *http.Response
}

// Receive is used to receive delta data.
func (s *ChatCompletionStream) Receive() (*ChatCompletionStreamResponse, error) {
	reader := bufio.NewReader(s.resp.Body)
	for {
		line, err := reader.ReadString('\n') // Read until newline
		if err != nil {
			if err == io.EOF {
				return nil, io.EOF
			}
			return nil, fmt.Errorf("failed to read stream: %s", err)
		}
		if line == "data: [DONE]" {
			return nil, io.EOF
		}
		if len(line) > 6 && line[:6] == "data: " {
			trimmed := []byte(line[6:])
			var resp ChatCompletionStreamResponse
			err = json.Unmarshal(trimmed, &resp)
			if err != nil {
				return nil, fmt.Errorf("unmarshal error: %s, raw data: %s", err, trimmed)
			}
			if resp.Usage == nil {
				resp.Usage = new(Usage)
			}
			return &resp, nil
		}
	}
}

// Close is used to close the response body.
func (s *ChatCompletionStream) Close() error {
	return s.resp.Body.Close()
}

// ChatCompletionStreamResponse represents a stream from the chat completion endpoint.
type ChatCompletionStreamResponse struct {
	// Type of the object, typically "chat.completion".
	Object string `json:"object"`

	// Unique identifier for the chat completion.
	ID string `json:"id"`

	// The model used for generating the completion.
	Model string `json:"model"`

	// List of completion choices generated by the model.
	Choices []*StreamChoice `json:"choices"`

	// Token usage statistics.
	Usage *Usage `json:"usage"`

	// Timestamp when the chat completion was created.
	Created int64 `json:"created"`
}

// StreamChoice represents a choice in the chat completion stream.
type StreamChoice struct {
	// Index of the choice.
	Index int `json:"index"`

	// Delta information for the choice.
	Delta *StreamDelta

	// Reason for finishing the generation.
	FinishReason string `json:"finish_reason,omitempty"`
}

// StreamDelta represents a delta in the chat completion stream.
type StreamDelta struct {
	// Role of the message.
	Role string `json:"role,omitempty"`

	// Content of the message.
	Content string `json:"content"`

	// Reasoning content of the message.
	ReasoningContent string `json:"reasoning_content,omitempty"`

	// Optional tool calls.
	ToolCalls []*ToolCall `json:"tool_calls,omitempty"`

	// Optional audio output.
	Audio *Audio `json:"audio,omitempty"`
}

// ToolCall represents a tool call in the completion.
type ToolCall struct {
	// Type of the tool call, e.g., "function".
	Type string `json:"type"`

	// Unique identifier for the tool call.
	ID string `json:"id"`

	// Index of the tool call.
	Index int `json:"index"`

	// The function details for the call.
	Function *ToolCallFunction `json:"function"`
}

// ToolCallFunction represents a function call in the tool.
type ToolCallFunction struct {
	// Name of the function (required).
	Name string `json:"name"`

	// JSON string of arguments passed to the function (required).
	Arguments string `json:"arguments"`
}

// Audio contains the output audio data.
type Audio struct {
	ID   string `json:"id"`
	Data string `json:"data"`
}

// Usage represents token usage statistics.
type Usage struct {
	// Number of tokens used in the prompt.
	PromptTokens int `json:"prompt_tokens"`

	// Number of tokens used in the completion.
	CompletionTokens int `json:"completion_tokens"`

	// Total number of tokens used.
	TotalTokens int `json:"total_tokens"`

	// ----------------DeepSeek----------------

	// Number of tokens served from cache.
	PromptCacheHitTokens int `json:"prompt_cache_hit_tokens"`

	// Number of tokens not served from cache.
	PromptCacheMissTokens int `json:"prompt_cache_miss_tokens"`

	// ---------------Xiaomi MiMo--------------

	PromptTokensDetails struct {
		CachedTokens int `json:"cached_tokens"`
		ImageTokens  int `json:"image_tokens"`
		AudioTokens  int `json:"audio_tokens"`
		VideoTokens  int `json:"video_tokens"`
	} `json:"prompt_tokens_details"`

	CompletionTokensDetails struct {
		ReasoningTokens int `json:"reasoning_tokens"`
	} `json:"completion_tokens_details"`
}
